pipeline {
    agent any
    
    tools{
        maven "Maven3.6.3"
    }

    stages {
	
		stage("Checkout code"){
			steps
			{
				checkout([$class: 'GitSCM', branches: [[name: '*/master-java']], extensions: [], userRemoteConfigs: [[credentialsId: 'd4d0bed4-0c49-4703-a79a-260f454ed606', url: 'https://git.nagarro.com/freshertraining2022/amritadas.git']]])
				echo 'Check Out'
			}
        }
        stage('Clean') {
            steps {
                sh 'mvn -f javaDemo/pom.xml clean'
                echo 'Cleaning..'
            }
        }
        stage('Compile') {
            steps {
                sh 'mvn -f javaDemo/pom.xml compile'
                echo 'Compiling..'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -f javaDemo/pom.xml test'
                echo 'Testing..'
            }
        }
        stage('Packaging') {
            steps {
                sh 'mvn -f javaDemo/pom.xml package'
                echo 'Packageing..'
            }
        }
        stage('Install') {
            steps {
                sh 'mvn -f javaDemo/pom.xml install'
                echo 'Installing..'
            }
        }
        
        
        stage('Juint result') {
            steps{
                junit 'javaDemo/target/surefire-reports/*.xml'
                echo 'Deploying....'
            }
        }
    }
}
